version: '3'
services:
  web:
    container_name: ${ENV_WEB_CONTAINER_NAME}
    build:
      context: ./nginx/
      args:
        ENV_DOCUMENT_ROOT: ${ENV_DOCUMENT_ROOT}
        ENV_SRC_DIRECTORY_NAME: ${ENV_SRC_DIRECTORY_NAME}
    image: ${ENV_WEB_IMAGE_NAME}
    env_file:
      - ./.env
    ports:
      - ${ENV_API_PORT}:80
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - api
    volumes:
      - ../project/backend:${ENV_DOCUMENT_ROOT}/${ENV_SRC_DIRECTORY_NAME}
    networks:
      - local-network

  api:
    container_name: ${ENV_API_CONTAINER_NAME}
    build:
      context: ./php/
      args:
        ENV_DB_CONNECTION: ${ENV_DB_CONNECTION}
        ENV_DB_HOST: ${ENV_DB_HOST}
        ENV_DB_PORT: 3306
        ENV_DB_DATABASE: ${ENV_DB_DATABASE}
        ENV_DB_USERNAME: ${ENV_DB_USERNAME}
        ENV_DB_PASSWORD: ${ENV_DB_PASSWORD}
        ENV_DB_ROOT_PASSWORD: ${ENV_DB_ROOT_PASSWORD}
        ENV_DOCUMENT_ROOT: ${ENV_DOCUMENT_ROOT}
        ENV_SRC_DIRECTORY_NAME: ${ENV_SRC_DIRECTORY_NAME}
    image: ${ENV_API_IMAGE_NAME}
    env_file:
      - ./.env
    volumes:
      - ../project/backend:${ENV_DOCUMENT_ROOT}/${ENV_SRC_DIRECTORY_NAME}
      - ./php/log/xdebug:/var/log/xdebug
    environment:
      TZ: ${ENV_TIMEZONE}
    stdin_open: true
    tty: true
    depends_on:
      - db
    networks:
      - local-network

  front:
    build:
      context: ./vuejs/
    container_name: ${ENV_FRONTEND_CONTAINER_NAME}
    image: ${ENV_FRONTEND_IMAGE_NAME}
    # env_file:
    #   - ./.env
    ports:
      - ${ENV_FRONTEND_PORT}:8080
    stdin_open: true
    tty: true
    volumes:
      - ../project/frontend:${ENV_DOCUMENT_ROOT}/${ENV_SRC_DIRECTORY_NAME}
      - node-module-volume:${ENV_DOCUMENT_ROOT}/${ENV_SRC_DIRECTORY_NAME}/node_modules
    networks:
      - local-network

  db:
    container_name: ${ENV_DB_CONTAINER_NAME}
    build: ./mariadb/
    image: ${ENV_DB_IMAGE_NAME}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - ${ENV_DB_PORT}:3306
    volumes:
      - ./mariadb/data/:/tmp/data/
    environment:
      MYSQL_DATABASE: ${ENV_DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${ENV_DB_ROOT_PASSWORD}
      MYSQL_USER: ${ENV_DB_USERNAME}
      MYSQL_PASSWORD: ${ENV_DB_PASSWORD}
    networks:
      - local-network

  # localstack:
  #   container_name: ${ENV_LOCALSTACK_CONTAINER_NAME}
  #   image: localstack/localstack
  #   ports:
  #     - 8080:8080 # dashboard
  #     - 4566:4566 # application
  #   environment:
  #     - SERVICES=s3,ses
  #     - AWS_ACCESS_KEY_ID=dummy
  #     - AWS_SECRET_ACCESS_KEY=dummy
  #     - AWS_DEFAULT_REGION=ap-northeast-1
  #     - DATA_DIR=/tmp/localstack/data
  #   volumes:
  #     - ./localstack/s3:/tmp/localstack
  #   networks:
  #     - local-network

  # awscli:
  #   container_name: ${ENV_AWSCLI_CONTAINER_NAME}
  #   image: xueshanf/awscli
  #   environment:
  #     - AWS_DEFAULT_REGION=ap-northeast-1
  #     - AWS_DEFAULT_OUTPUT=json
  #     - AWS_ACCESS_KEY_ID=dummy
  #     - AWS_SECRET_ACCESS_KEY=dummy
  #   volumes:
  #     - ./localstack/sample_img:/tmp/sample_img
  #   depends_on:
  #     - localstack
  #   entrypoint: /bin/sh -c "while :; do sleep 10; done"
  #   networks:
  #     - local-network

volumes:
  node-module-volume:
    driver: local
networks:
  local-network:
    driver: bridge